// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stackheight.proto

#ifndef PROTOBUF_INCLUDED_stackheight_2eproto
#define PROTOBUF_INCLUDED_stackheight_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_stackheight_2eproto 

namespace protobuf_stackheight_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_stackheight_2eproto
namespace stackheight {
class Height;
class HeightDefaultTypeInternal;
extern HeightDefaultTypeInternal _Height_default_instance_;
class StackHeights;
class StackHeightsDefaultTypeInternal;
extern StackHeightsDefaultTypeInternal _StackHeights_default_instance_;
}  // namespace stackheight
namespace google {
namespace protobuf {
template<> ::stackheight::Height* Arena::CreateMaybeMessage<::stackheight::Height>(Arena*);
template<> ::stackheight::StackHeights* Arena::CreateMaybeMessage<::stackheight::StackHeights>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace stackheight {

// ===================================================================

class Height : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:stackheight.Height) */ {
 public:
  Height();
  virtual ~Height();

  Height(const Height& from);

  inline Height& operator=(const Height& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Height(Height&& from) noexcept
    : Height() {
    *this = ::std::move(from);
  }

  inline Height& operator=(Height&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Height& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Height* internal_default_instance() {
    return reinterpret_cast<const Height*>(
               &_Height_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Height* other);
  friend void swap(Height& a, Height& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Height* New() const final {
    return CreateMaybeMessage<Height>(NULL);
  }

  Height* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Height>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Height& from);
  void MergeFrom(const Height& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Height* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 address = 1;
  void clear_address();
  static const int kAddressFieldNumber = 1;
  ::google::protobuf::int64 address() const;
  void set_address(::google::protobuf::int64 value);

  // int64 height = 2;
  void clear_height();
  static const int kHeightFieldNumber = 2;
  ::google::protobuf::int64 height() const;
  void set_height(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:stackheight.Height)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 address_;
  ::google::protobuf::int64 height_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_stackheight_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StackHeights : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:stackheight.StackHeights) */ {
 public:
  StackHeights();
  virtual ~StackHeights();

  StackHeights(const StackHeights& from);

  inline StackHeights& operator=(const StackHeights& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StackHeights(StackHeights&& from) noexcept
    : StackHeights() {
    *this = ::std::move(from);
  }

  inline StackHeights& operator=(StackHeights&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StackHeights& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StackHeights* internal_default_instance() {
    return reinterpret_cast<const StackHeights*>(
               &_StackHeights_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(StackHeights* other);
  friend void swap(StackHeights& a, StackHeights& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StackHeights* New() const final {
    return CreateMaybeMessage<StackHeights>(NULL);
  }

  StackHeights* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StackHeights>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StackHeights& from);
  void MergeFrom(const StackHeights& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StackHeights* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .stackheight.Height heights = 1;
  int heights_size() const;
  void clear_heights();
  static const int kHeightsFieldNumber = 1;
  ::stackheight::Height* mutable_heights(int index);
  ::google::protobuf::RepeatedPtrField< ::stackheight::Height >*
      mutable_heights();
  const ::stackheight::Height& heights(int index) const;
  ::stackheight::Height* add_heights();
  const ::google::protobuf::RepeatedPtrField< ::stackheight::Height >&
      heights() const;

  // @@protoc_insertion_point(class_scope:stackheight.StackHeights)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::stackheight::Height > heights_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_stackheight_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Height

// int64 address = 1;
inline void Height::clear_address() {
  address_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Height::address() const {
  // @@protoc_insertion_point(field_get:stackheight.Height.address)
  return address_;
}
inline void Height::set_address(::google::protobuf::int64 value) {
  
  address_ = value;
  // @@protoc_insertion_point(field_set:stackheight.Height.address)
}

// int64 height = 2;
inline void Height::clear_height() {
  height_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Height::height() const {
  // @@protoc_insertion_point(field_get:stackheight.Height.height)
  return height_;
}
inline void Height::set_height(::google::protobuf::int64 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:stackheight.Height.height)
}

// -------------------------------------------------------------------

// StackHeights

// repeated .stackheight.Height heights = 1;
inline int StackHeights::heights_size() const {
  return heights_.size();
}
inline void StackHeights::clear_heights() {
  heights_.Clear();
}
inline ::stackheight::Height* StackHeights::mutable_heights(int index) {
  // @@protoc_insertion_point(field_mutable:stackheight.StackHeights.heights)
  return heights_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::stackheight::Height >*
StackHeights::mutable_heights() {
  // @@protoc_insertion_point(field_mutable_list:stackheight.StackHeights.heights)
  return &heights_;
}
inline const ::stackheight::Height& StackHeights::heights(int index) const {
  // @@protoc_insertion_point(field_get:stackheight.StackHeights.heights)
  return heights_.Get(index);
}
inline ::stackheight::Height* StackHeights::add_heights() {
  // @@protoc_insertion_point(field_add:stackheight.StackHeights.heights)
  return heights_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::stackheight::Height >&
StackHeights::heights() const {
  // @@protoc_insertion_point(field_list:stackheight.StackHeights.heights)
  return heights_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace stackheight

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_stackheight_2eproto
