# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stackheight.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stackheight.proto',
  package='stackheight',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11stackheight.proto\x12\x0bstackheight\")\n\x06Height\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x03\x12\x0e\n\x06height\x18\x02 \x01(\x03\"4\n\x0cStackHeights\x12$\n\x07heights\x18\x01 \x03(\x0b\x32\x13.stackheight.Heightb\x06proto3')
)




_HEIGHT = _descriptor.Descriptor(
  name='Height',
  full_name='stackheight.Height',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='stackheight.Height.address', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='stackheight.Height.height', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=75,
)


_STACKHEIGHTS = _descriptor.Descriptor(
  name='StackHeights',
  full_name='stackheight.StackHeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heights', full_name='stackheight.StackHeights.heights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=129,
)

_STACKHEIGHTS.fields_by_name['heights'].message_type = _HEIGHT
DESCRIPTOR.message_types_by_name['Height'] = _HEIGHT
DESCRIPTOR.message_types_by_name['StackHeights'] = _STACKHEIGHTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Height = _reflection.GeneratedProtocolMessageType('Height', (_message.Message,), dict(
  DESCRIPTOR = _HEIGHT,
  __module__ = 'stackheight_pb2'
  # @@protoc_insertion_point(class_scope:stackheight.Height)
  ))
_sym_db.RegisterMessage(Height)

StackHeights = _reflection.GeneratedProtocolMessageType('StackHeights', (_message.Message,), dict(
  DESCRIPTOR = _STACKHEIGHTS,
  __module__ = 'stackheight_pb2'
  # @@protoc_insertion_point(class_scope:stackheight.StackHeights)
  ))
_sym_db.RegisterMessage(StackHeights)


# @@protoc_insertion_point(module_scope)
